export type Mode = 'hype' | 'rage';
export type Lang = 'en' | 'th';
export type PackName = 'overwatch' | 'dota2' | 'lol';

interface SentenceSet {
  neutral: string[];
  hype: string[];
  rage: string[];
}

interface SentencePack {
  en: SentenceSet;
  th: SentenceSet;
}

const _ow: SentencePack = {
  en: {
    neutral: [
      'push payload push push',
      'i need heals brooo',
      'ult ready, wait for my call',
      'group up first dont stagger',
      'genji flanking right side',
      'mercy dead mercy dead go go',
      'who wants tank',
      'ana slept reaper free kill',
      'shield gone back up back up',
      'nano coming go in go in',
      'one more fight boys',
      'pharah free firing up there',
      'mei wall choke pls',
      'tracer on our backline',
      'sigma cooking our whole team',
      'reset reset dont feed',
      'wait for tank before pushing',
      'cass low cass low',
      'mercy one mercy one',
      'play point play point',
      'widow top left careful',
      'dont use ult lost fight',
      'i got beat for next fight',
      'touch touch touch',
      'their kiri has no suzu',
      'focus the supports first',
      'we can win this easy',
      'backline needs help',
      'hold corners dont peek',
      'save ults for overtime',
    ],
    hype: [
      'yo that was clean as hell',
      'huge rez holy shit',
      'team diff lets goooo',
      'we are so back',
      'that nano blade was disgusting',
      'clean wipes all game',
      'good comms good vibes',
      'ggs yall played great',
      'all good next round comeback time',
      'we got momentum now',
      'our tank is cooking',
      'support line carrying rn',
      'big shatter hugeee',
      'thats the play right there',
      'we are rolling them',
      'insane clutch omg',
      'widow woke up finally',
      'that save was massive',
      'beautiful ult combo',
      'nah this team actually good',
      'keep this energy up',
      'that was peak overwatch',
      'lets close this out',
      'yall locked in now',
      'crazy hold boys',
      'we winning this 100%',
      'thats my team right there',
      'holy aim',
      'everyone popped off that fight',
      'comeback goes crazy',
    ],
    rage: [
      'support diff',
      'tank diff',
      'damage diff',
      'why is no one on point lol',
      'enemy team has six dps, what a joke',
      'absolute dogwater team',
      'this dps is feeding sooo hard',
      'unbelievable b**chmade play',
      'how do you miss that shot',
      'NPC behavior from our tank',
      'skill issue',
      'this team is cooked',
      'bro got negative aim assist',
      'our widow is legally blind',
      'tank pressing W with no thoughts',
      'who gave this genji confidence',
      'healing output sponsored by thoughts and prayers',
      'stop staggering holy hell',
      'this lobby feels like quick play bronze',
      'rein charging into five people again',
      'mercy pocketing the worst player alive',
      'this sombra is playing hide and seek',
      'we got spectating simulator teammates',
      'zero awareness team comp',
      'somebody unplug our hanzo',
      'tank diff so hard it needs subtitles',
      'this ana sleeps everyone except the enemy',
      'team allergic to payload',
      'who invited this guy to ranked',
      'genji asking for nano after going 2-9',
      'this team fights like a school project group',
      'support line fighting for their lives back there',
      'please uninstall reaper immediately',
      'bro got rolled and typed ez',
      'this junkrat has more deaths than damage',
      'widow missing shots in 4k',
      'tank line weaker than wet cardboard',
      'doomfist in, doomfist dead, repeat',
      'this push has the energy of a retirement home',
      'peak clown queue gameplay',
      'teammates moving like background NPCs',
      'everyone pressing Q in lost fights',
      'i have seen bots with better rotations',
      'our defense folded instantly',
      'this match is a psychological experiment',
      'enemy tracer farming clips on us',
      'that was NOT a top 500 play',
    ],
  },
  th: {
    neutral: [
      'ดันเพย์โหลด ดันๆๆ',
      'ขอฮีลหน่อยยย',
      'อัลติพร้อม รอเข้าไฟต์พร้อมกัน',
      'รวมก่อนๆ อย่าเพิ่งเข้า',
      'เก็นจิอ้อมขวา ระวังหลัง',
      'เมอร์ซี่ตายแล้ว เข้าได้',
      'ถอยก่อน รีกรุ๊ปๆ',
      'โล่แตกละ ถอยๆ',
      'นาโน่มา ลุยเลยย',
      'ซิกม่าใกล้ตาย ดันได้',
      'อีกนิดเดียววว',
      'อย่าแยกๆ',
      'เล่นช้าได้ ไม่ต้องรีบ',
      'เดี๋ยวผมเปิดให้',
      'มีคนดักหลังนะ',
      'เมอร์ซี่เลืิิอด 1',
      'ขอคนไปเก็บ widow หน่อย',
      'ระวังหลัง',
      'เข้า point เลยๆ',
      'ผมมี nano ใครเอา',
      'เก็บซัพก่อนๆ',
      'อย่ากดอัลติมั่วนะ',
      'ซัพโดนล้วง ช่วยที',
      'รอแทงค์ก่อนนน',
      'หลังๆๆ tracer หลัง',
      'คุม high ground กัน',
    ],
    hype: [
      'โคตรสวยยย',
      'ซัพดีจัด ขอบคุณมาก',
      'เล่นดีว่ะทีมนี้',
      'ไฟต์นี้โคตรหล่อ',
      'นาโน่อย่างสวย',
      'ทีมเวิร์คโคตรดี',
      'จีจีๆ เล่นดีทุกคน',
      'ไม่เป็นไร เอาใหม่ได้',
      'เกือบได้ๆ สู้ต่อ',
      'โห คมจัด',
      'ช็อตเมื่อกี้อย่างแบก',
      'ซัพแบกจัดเกมนี้',
      'แทงค์เปิดสวยมาก',
      'ดาเมจอย่างตึง',
      'เกิ๊นนนนนน',
      'แผนนี้เวิร์คว่ะ',
      'เล่นแบบนี้ขึ้นแรงค์แน่',
      'โอเคเลยตานี้',
      'ทีมนี้มีของ',
      'สุดจัดดด',
      'เมอร์ซี่ชุบทันได้ไง โคตรเทพ',
      'ไฟต์คัมแบ็คโคตรเดือด',
      'อย่างเอาาา',
      'สวยพี่ สวยมาก',
      'รักซัพเกมนี้',
      'อัลติคอมโบโคตรดี',
      'เออออ แบบนี้แหละ',
      'ตานี้เข้ามือแล้ว',
      'โคตรมันส์',
    ],
    rage: [
      'ควยเหอะ ทีมกาก',
      'ควย ควย ควย',
      'ควยยยยยยย',
      'ซัพทำไรอยู่วะ',
      'แทงค์เปิดอะไรของมึง',
      'ดาเมจยิงลมอยู่ปะ',
      'เมอร์ซี่ฮีลบ้างป่ะเนี่ย',
      'แบกไม่ไหว',
      'เล่นเหมือนต่อจอยให้หมา',
      'ยิงไม่โดนสักนัด เอาจริงดิ',
      'แจกแต้ม',
      'โคตร diff',
      'กูแบกจนหลังหักละ',
      'เข้าแรงค์มาเพื่อโยนใช่ปะ',
      'กดอัลต์ใส่ใคร',
      'เล่นเป็นป่ะเนี่ย',
      'ทีมแม่งยืนดู payload',
      'เล่นเหมือนบอท',
      'คิวแรงค์มาเพื่อทำกูหัวร้อน',
      'ยิงเมอร์ซี่ก่อนดิวะะะ',
      'กูไม่น่ากดเล่นวันนี้เลย',
      'doom กาก',
      'ทีมแตกตั้งแต่เลือกตัว',
      'เห็นสกอร์ละอยากปิดเกม',
      'โคตรสวะ',
      'เล่นเหมือนไม่มีหูฟัง',
      'ใครชวนเกนจิมาแรงค์',
      'เมิงยิงโดนบ้างก็ได้',
      'แม่ง NPC ทั้งทีม',
      'เกมนี้กู 1v9 ของจริง',
      'ควยเอ้ย อีกละ',
      'แม่งเอ้ย',
      'ควยไรเนี่ย',
      'โคตรควาย',
      'เหี้ยจัดเกมนี้',
      'ควย เกมกาก คนก็กาก',
      'ช่วยใช้สมองเล่นหน่อย',
      'เล่นกากอย่าปากเก่ง',
      'กากทั้งเกมยังพิมพ์ ez',
      'แม่งเดินเข้าไปตายฟรีอีกละ',
      'ซัพหายไปไหนของแม่ง',
      'ไอ้สัส เข้า point ก่อนนน',
      'ควยเอ้ย โดนล้วงฟรีอีก',
      'แม่งเล่นเหมือนจอไม่เปิด',
      'อัลติมั่วชิบหาย',
      'กูเหนื่อยแทนซัพ',
      'แม่งไม่ดูหลังเลย',
      'เดินแยกทีละคน จะชนะยังไง',
      'ปิดเกมไปเล่น roblox ไป'
    ],
  },
};

const _dota: SentencePack = {
  en: {
    neutral: [
      'gank mid please',
      'rosh up in two minutes',
      'ward the enemy jungle now',
      'smoke gank top',
      'buy bkb or we lose',
      'tp coming, hold the tower',
      'glyph the rax',
      'aegis on the carry',
      'jungle creeps stacked for you',
      'enemy tinker has aghs',
    ],
    hype: [
      'great farm carry, we win this',
      'amazing teamfight, all in',
      'clutch rosh, lets push',
      'support is goated, mvp',
      'incredible hook from pudge',
      'gg well played team',
      'one more push and we win',
    ],
    rage: [
      'support diff, no wards all game',
      'pos five buy mango stop being lazy',
      'mid is lost, play passive scrub',
      'why are we still farming, throw',
      'tower diving is throwing the game',
      'this carry is absolute trash',
      'report this pos five for griefing',
      'cope and seethe, we lose',
    ],
  },
  th: {
    neutral: [
      'แกงค์มิดที',
      'โรชอีก 2 นาที',
      'วอร์ดป่าเลย',
      'สโมคแกงค์ท็อป',
      'ซื้อบีเคบีเร็ว',
      'ทีพีมา รออยู่',
      'อีจิสให้แครี่',
    ],
    hype: [
      'แครี่ฟาร์มสวยมาก',
      'ทีมไฟท์เยี่ยม ลุยต่อ',
      'จีจี เกมส์สวย',
      'อีกพุชเดียวชนะ',
    ],
    rage: [
      'ซัพห่วยทั้งเกม ไม่มีวอร์ด',
      'มิดแตก เล่นเซฟๆ',
      'ทำไมยังฟาร์มอีก โยน',
      'แครี่ห่วยมาก',
      'รีพอร์ตคนนี้',
    ],
  },
};

const _lol: SentencePack = {
  en: {
    neutral: [
      'baron in thirty seconds',
      'dragon up, group mid',
      'enemy jg botside, ward',
      'i need a gank top',
      'flash is down on their mid',
      'wombo combo on three',
      'group for objective please',
      'one more wave then back',
      'we have herald, take tower',
      'ping the missing enemy',
    ],
    hype: [
      'amazing teamfight, lets goooo',
      'clean baron steal, mvp',
      'support carrying this game',
      'gg team we win this',
      'incredible flash combo',
      'this game is so winnable lets focus',
    ],
    rage: [
      'jg diff, no ganks all game',
      'why are you splitpush there, throw',
      'all chat: ez gg report mid',
      'this adc is absolute dogwater',
      'support diff every game lol',
      'b**chmade engage, we lose',
      'cope and ff15, this is over',
      'NPC support, never roams',
    ],
  },
  th: {
    neutral: [
      'บารอนอีกครึ่งนาที',
      'ดราก้อนมา รวมมิด',
      'จังเกิ้ลเขาอยู่บอท',
      'ขอแกงค์ท็อปที',
      'แฟลชเขาหมด',
      'รวมตัวเอาออบเจกต์',
    ],
    hype: [
      'ทีมไฟท์สวยมาก',
      'จีจี ทีมเก่ง',
      'ซัพคาร์รี่เกม',
      'อีกเวฟเดียว แล้วเบส',
    ],
    rage: [
      'จังเกิ้ลห่วย ไม่แกงค์เลย',
      'แอดซีห่วยมาก',
      'ซัพห่วยทุกเกม',
      'FF เถอะ จบแล้ว',
    ],
  },
};

export const SENTENCE_PACKS: Record<PackName, SentencePack> = {
  overwatch: _ow,
  dota2: _dota,
  lol: _lol,
};

export function getSentencePool(pack: PackName, lang: Lang, mode: Mode): string[] {
  const p = SENTENCE_PACKS[pack][lang];
  return [...p.neutral, ...p[mode]];
}

export const AMBIENT_CHAT: Record<Mode, Record<Lang, string[]>> = {
  hype: {
    en: [
      'nice shotttt',
      'huge play',
      'W team',
      'we got this boys',
      'clean af',
      'good shit team',
      'thats my tank',
      'support carry fr',
      'crazy clutch',
      'good comms',
      'we are LOCKED IN',
      'yo that combo was nasty',
      'keep cooking',
      'we rolling them',
      'actual dream team',
      'good reset good reset',
      'huge rez omg',
      'big shatterrrrr',
      'we are so back',
      'nah yall cracked',
      'massive hold',
      'that aim is illegal',
      'best randoms ever',
      'one more push we win',
      'holy carry',
      'peak overwatch',
      'lets fucking gooooo',
      'tank diff OUR WAY',
      'this team got aura',
      'everyone popped off',
    ],

    th: [
      'ช็อตสวยยย',
      'ทีมโคตรดี',
      'เออออ แบบนี้แหละ',
      'อย่างเอาาา',
      'เล่นดีจัด',
      'ไฟต์นี้โคตรหล่อ',
      'ซัพแบกจัด',
      'แทงค์เปิดสวยมาก',
      'โคตร clutch',
      'รักทีมนี้ว่ะ',
      'คอมโบอย่างสวย',
      'จีจีๆ เล่นดีทุกคน',
      'เอาอีกๆ กำลังเข้ามือ',
      'โคตรมันส์',
      'อย่างตึงงง',
      'รีซทันได้ไง โคตรเทพ',
      'แบกจัดพี่',
      'โอ้โหหหห',
      'เล่นแบบนี้ขึ้นแรงค์แน่',
      'ตานี้ของจริง',
      'ทีมนี้มีของ',
      'เดือดจัด',
      'สวยพี่ สวยมาก',
      'เอาอยู่ๆ',
      'ยิงคมจัด',
      'คัมแบ็คได้ชัวร์',
      'ดาเมจเข้าแล้วว',
      'ไฟต์นี้กินขาด',
      'แม่งโคตรเท่',
      'สุดจัดดด',
    ],
  },

  rage: {
    en: [
      'what the hell was that',
      'bro is LOST',
      'uninstall immediately',
      'trash ass team',
      'support diff',
      'tank diff gg',
      'dps shooting ghosts',
      'who invited this guy',
      'actual npc behavior',
      'stop feeding holy',
      'widow missing in 4k',
      'doomfist in -> dead',
      'team allergic to payload',
      'why are we staggering',
      'gg go next',
      'im in elo hell',
      'this lobby is cursed',
      'we got quickplay teammates',
      'zero awareness',
      'negative aim',
      'heals?? hello??',
      'bro used ult for decoration',
      'this team is cooked',
      'cant carry this',
      'everyone pressing Q in lost fights',
      'enemy mercy immortal or what',
      'report my mental health after this',
      'afk simulator',
      'never let bro cook again',
      'this match aging me 10 years',
    ],

    th: [
      'ควยเหอะ ทีมกาก',
      'พ่อง แม่ง',
      'แม่งเอ้ย',
      'ทีมห่วยชิบหาย',
      'แทงค์หลับปะเนี่ย',
      'ดีพีเอสยิงลมอยู่',
      'ซัพหายไปไหน',
      'ช่วยเข้า point ที',
      'โยนกันจัดๆ',
      'เล่นเหมือนบอท',
      'NPC ทั้งทีม',
      'กูแบกจนหลังหัก',
      'เกมนี้แจกดาวชัดๆ',
      'ยิงไม่โดนได้ไงวะ',
      'ควย ควย ควย',
      'FF เถอะ จบๆ',
      'กูจะบ้า',
      'ตายต้นไฟต์อีกละ',
      'เล่นเหมือนไม่เปิดจอ',
      'เมอร์ซี่ปั๊มคนกากทั้งเกม',
      'อีกทีมเล่นเป็น ทีมกูเล่นไร',
      'ใครแม่งกดแรงค์มา',
      'กูไม่น่าคิวเลย',
      'โดน tracer ฟาร์มฟรี',
      'สกิลอิชชู่ของแท้',
      'แตกตั้งแต่เลือกตัว',
      'อัลต์มั่วชิบหาย',
      'ทีมนี้ IQ รวมไม่ถึง 10',
      'เอาเมาส์เท้าวาดยังดีกว่า',
      'โคตร bronze mindset',
    ],
  },
};

export const CHAT_AUTHORS: Record<'ally' | 'enemy', Array<{ name: string; role: string }>> = {
  ally: [
    { name: 'Mochi_main',  role: 'TANK' },
    { name: 'sleepywidow', role: 'DPS'  },
    { name: 'mercy.btw',   role: 'SUP'  },
    { name: 'jungleDad',   role: 'JG'   },
    { name: 'ezreal_one',  role: 'ADC'  },
    { name: 'kookkook',    role: 'MID'  },
    { name: 'pos5_andy',   role: 'SUP'  },
  ],
  enemy: [
    { name: 'xX_endmeXx',   role: 'DPS'   },
    { name: 'urmom_2k',     role: 'MID'   },
    { name: 'reportedlol',  role: 'JG'    },
    { name: 'cancel.queue', role: 'TOP'   },
    { name: 'iddqd_69',     role: 'CARRY' },
    { name: 'sleepyhanzo',  role: 'DPS'   },
  ],
};

export const BOSSES: Record<Mode, { name: string; tag: string; color: string }> = {
  hype: { name: 'COACH_GG',     tag: 'mentor',   color: '#7CFF3F' },
  rage: { name: 'xX_DESTROYER', tag: 'unhinged', color: '#FF2D2D' },
};
